### ISSUE TITLE
package: ssr.netlify

### ISSUE THREAD

**Issue by lukeed** [lukeed/freshie#12]
Much like `ssr.vercel` – this _might_ be able to get away with reusing/reexporting the `ssr.lambda` code, but it has to deal with a config file(s):

```toml
# netlfy.toml
# needs testing
[build]
  functions = "build/server"
```

There's also [Edge Handlers](https://www.netlify.com/products/edge/edge-handlers/) coming soon(?). Haven't got my hands on them yet, but will need to be its own package, since it has more of a Cloudflare Worker API than a Lambda API.
Maybe `ssr.netlify.edge` ?
